<a href="https://colab.research.google.com/github/hongwon2/Python-Practice/blob/main/%EC%9C%A0%ED%8C%90_%EB%84%98%ED%8C%8C%EC%9D%B4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

In [5]:
v1 =np.array([1,2,3,4])

In [6]:
print(v1)

[1 2 3 4]


In [9]:
v1 = np.arange(5)

In [10]:
print(v1)

[0 1 2 3 4]


In [13]:
v2 = np.arange(1,10,2)**3
print(v2)

[  1  27 125 343 729]


In [15]:
v1 = np.arange(12)
v1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
v2 = v1.reshape(2,6,order = 'F')
v2

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

In [22]:
v1 = np.arange(1,5)
v2 = v1.reshape(2,2)
v2

array([[1, 2],
       [3, 4]])

In [23]:
v3 = np.arange(1,5).reshape(2,2)
v3

array([[1, 2],
       [3, 4]])

In [25]:
print(np.add(v2,v2))

[[2 4]
 [6 8]]


In [27]:
print(np.subtract(v2,v2))

[[0 0]
 [0 0]]


In [29]:
print(np.multiply(v2,v2))

[[ 1  4]
 [ 9 16]]


In [30]:
print(np.dot(v2,v2))

[[ 7 10]
 [15 22]]


In [31]:
v1 = np.arange(12)
v1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [33]:
v2 = v1.reshape(2,3,2,order = 'F')
v2

array([[[ 0,  6],
        [ 2,  8],
        [ 4, 10]],

       [[ 1,  7],
        [ 3,  9],
        [ 5, 11]]])

In [35]:
v3 = np.arange(3.5,10.5,2,dtype = float)
print(v3)

[3.5 5.5 7.5 9.5]


In [37]:
v4 = v3.reshape(2,2)
v4

array([[3.5, 5.5],
       [7.5, 9.5]])

In [38]:
print(np.amax(v4))

9.5


In [40]:
print(v4.shape)

(2, 2)
